export const TOGGLE_CART_HIDDEN = 'TOGGLE_CART_HIDDEN';

export const ADD_ITEMS_REQUEST = 'ADD_ITEMS_REQUEST';
export const ADD_ITEMS = 'ADD_ITEMS';

export const REMOVE_ITEMS_REQUEST = 'REMOVE_ITEMS_REQUEST';
export const REMOVE_ITEMS = 'REMOVE_ITEMS';

export const DELETE_ITEMS_FROM_CART_REQUEST = 'DELETE_ITEMS_FROM_CART_REQUEST';
export const DELETE_ITEMS_FROM_CART = 'DELETE_ITEMS_FROM_CART';

export const CLEAR_CART = 'CLEAR_CART';
