export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const COLLECTION_LIST_REQUEST = 'COLLECTION_LIST_REQUEST';
export const COLLECTION_LIST_SUCCESS = 'COLLECTION_LIST_SUCCESS';
export const COLLECTION_LIST_FAIL = 'COLLECTION_LIST_FAIL';
